apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid
spec:
  replicas: 2
  selector:
    matchLabels:
      app: covid
  template:
    metadata:
      labels:
        app: covid
    spec:
      containers:
        - name: covid
          # image: gcr.io/msa-archi/41/covid:1
          image: amyik/covid
          imagePullPolicy: Always
          # imagePullPolicy: Never
          # imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 5000
          # - containerPort: 8090
          env:
            # - name: URL_CARTSERVICE
            #   value: http://eshop-cartservice:8091
            # - name: URL_PRODUCTSERVICE
            #   value: http://eshop-productservice:8092
            # - name: NATS_SPRING_SERVER
            #   value: "nats://nats-cluster.default.svc.cluster.local:4222"
          resources:
            requests:
              cpu: 500m
              memory: 384Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
---
apiVersion: v1
kind: Service
metadata:
  name: covid
spec:
  type: NodePort
  selector:
    app: covid
  ports:
  - port: 8090
    nodePort: 30080
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: covid
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: covid
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50