apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid
  # namespace: myspace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: covid
  template:
    metadata:
      labels:
        app: covid
    spec:
      containers:
        - name: covid
          image: amyik/covid:kfs
          imagePullPolicy: Always
          ports:
          - containerPort: 5000
          env:
          resources:
            requests:
              cpu: 500m
              memory: 384Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
---
apiVersion: v1
kind: Service
metadata:
  name: covid
  # namespace: myspace
spec:
  type: NodePort
  selector:
    app: covid
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30080
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: covid
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: covid
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
  