# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: covid19-fastapi
#   namespace: myspace
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: covid19-fastapi
#   template:
#     metadata:
#       labels:
#         app: covid19-fastapi
#     spec:
#       containers:
#         - name: covid19-fastapi
#           image: kubeflow-registry.default.svc.cluster.local:30000/covid-fastapi
#           ports:
#           - containerPort: 8000
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: covid19-fastapi
#   namespace: myspace
# spec:
#   type: ClusterIP
#   selector:
#     app: covid19-fastapi
#   ports:
#   - port: 8000
# ---
# apiVersion: autoscaling/v1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: covid19-fastapi
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: covid19-fastapi
#   minReplicas: 2
#   maxReplicas: 4
#   targetCPUUtilizationPercentage: 50