apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid-fast
  namespace: myspace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: covid-fast
  template:
    metadata:
      labels:
        app: covid-fast
    spec:
      containers:
        - name: covid-fast
          image: amyik/covid:fast
          imagePullPolicy: Always
          ports:
          - containerPort: 8000
          resources:
            requests:
              cpu: 500m
              memory: 384Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
---
apiVersion: v1
kind: Service
metadata:
  name: covid-fast
  namespace: myspace
spec:
  # type: NodePort
  type: ClusterIP
  selector:
    app: covid-fast
  ports:
  - port: 8000
    # targetPort: 5000
    # nodePort: 30080
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: covid-fast
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: covid-fast
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50